#!/usr/bin/env python3
"""abbrevs: the shortest spelling of every FastBasic keyword, read from the grammar itself.

FastBasic's syntax files (`src/syntax/*.syn` in the source, `syntax/` next to the compiler in a
release) write every keyword with its required part in UPPERCASE and its optional part in
lowercase: "PMGraphics" can be typed PMG., PMGR., ... or PMGRAPHICS. So the shortest form is the
uppercase prefix plus a dot, or the whole word when it has no lowercase part (INC, DO, END).

  abbrevs.py SYNTAX_DIR [--target atari-int] > docs/abbreviations.md

The table is grouped by where the word is valid (statement, function, operator...), because
the same abbreviation means different things in different places: P. is POKE as a
statement and PEEK in an expression.
"""
import argparse, glob, os, re, sys

TARGET_FILES = {
    'atari-int': ['a800', 'basic', 'dli', 'fileio', 'pm', 'graphics', 'sound', 'extended', 'sio'],
    'atari-fp': ['a800', 'basic', 'dli', 'fileio', 'pm', 'graphics', 'sound', 'extended', 'sio',
                 'float', 'fujinet'],
}

CONTEXT = [  # (rule-name pattern, label)
    (r'^(STATEMENT|EXEC_CALL)$', 'statement'),
    (r'FUNCTIONS?$|^FP_FUNCS$|^FP_T_EXPR$|^T_EXPR$', 'function'),
    (r'EXPR_MORE$|_RIGHT$|^NOT_EXPR$', 'operator'),
]


def shortest(tok):
    m = re.match(r'([^a-z]*)([a-z].*)?$', tok)
    req, opt = m.group(1), m.group(2)
    return req + '.' if opt else req


def scan(path):
    rule = None
    text = open(path, encoding='latin1').read().replace('\\\n', ' ')   # join continued lines
    for line in text.split('\n'):
        code = line.split('#')[0]
        m = re.match(r'^([A-Z_][A-Z0-9_]*)\s*:', code)
        if m:
            rule = m.group(1); continue
        if not code.strip() or rule is None:
            continue
        for k, m in enumerate(re.finditer(r'"([^"]*)"', code)):
            t = m.group(1)
            if re.search(r'[A-Za-z]', t):
                # only the word that starts an alternative names it (FOR yes, TO no)
                first = code[:m.start()].strip() == ''
                yield (rule if first else rule + ' (inside)'), t


def label(rule):
    for pat, lab in CONTEXT:
        if re.search(pat, rule):
            return lab
    return 'other'


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('syntax_dir'); ap.add_argument('--target', default='atari-int', choices=TARGET_FILES)
    a = ap.parse_args()
    rows = {}
    for f in TARGET_FILES[a.target]:
        p = os.path.join(a.syntax_dir, f + '.syn')
        if not os.path.exists(p):
            continue
        for rule, t in scan(p):
            full = t.upper()
            key = (label(rule), full)
            if key not in rows:
                rows[key] = (shortest(t), f, rule)
    print(f'# FastBasic abbreviations ({a.target})\n')
    print('Generated by `tools/abbrevs.py` from the FastBasic grammar files. "Shortest" is what '
          'a minimizer writes; any longer prefix ending in a dot works too. "Rule" is the '
          'grammar rule the word appears in.\n')
    print('Two statements have a symbol that beats any abbreviation: `?` is PRINT and `@` is '
          'EXEC (`@P` calls PROC P). A word with no dot in the Shortest column has no '
          'abbreviation: write it out (`INC`, `DO`, `END`).\n')
    order = ['statement', 'function', 'operator', 'other']
    for lab in order:
        items = sorted((k[1], v) for k, v in rows.items() if k[0] == lab)
        if not items:
            continue
        print(f'## {lab.capitalize()}s\n' if lab != 'other' else '## Other words\n')
        print('| Word | Shortest | Saves | Rule | File |\n|---|---|---|---|---|')
        for full, (s, f, rule) in items:
            print(f'| `{full}` | `{s}` | {len(full) - len(s)} | {rule} | {f}.syn |')
        print()


if __name__ == '__main__':
    main()
